# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_loader_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

from source.main.video_process_label import VideoLabel


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(891, 653)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.bar_graph = QtWidgets.QWidget()
        self.bar_graph.setObjectName("bar_graph")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.bar_graph)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.team_a_graph = QtWidgets.QLabel(self.bar_graph)
        self.team_a_graph.setObjectName("team_a_graph")
        self.verticalLayout_4.addWidget(self.team_a_graph)
        self.team_b_graph = QtWidgets.QLabel(self.bar_graph)
        self.team_b_graph.setObjectName("team_b_graph")
        self.verticalLayout_4.addWidget(self.team_b_graph)
        self.tabWidget_2.addTab(self.bar_graph, "")
        self.line_graph = QtWidgets.QWidget()
        self.line_graph.setObjectName("line_graph")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.line_graph)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.player_graph = QtWidgets.QLabel(self.line_graph)
        self.player_graph.setObjectName("player_graph")
        self.verticalLayout_5.addWidget(self.player_graph)
        self.tabWidget_2.addTab(self.line_graph, "")
        self.gridLayout.addWidget(self.tabWidget_2, 0, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setObjectName("tabWidget")
        self.origin_view = QtWidgets.QWidget()
        self.origin_view.setObjectName("origin_view")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.origin_view)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.video_frame1 = QtWidgets.QLabel(self.origin_view)
        self.video_frame1.setObjectName("video_frame1")
        self.verticalLayout_2.addWidget(self.video_frame1)
        self.tabWidget.addTab(self.origin_view, "")
        self.processing_view = QtWidgets.QWidget()
        self.processing_view.setObjectName("processing_view")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.processing_view)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        # self.video_frame2 = QtWidgets.QLabel(self.processing_view)
        self.video_frame2 = VideoLabel(self.processing_view)
        self.video_frame2.setObjectName("video_frame2")
        self.verticalLayout_3.addWidget(self.video_frame2)
        self.tabWidget.addTab(self.processing_view, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalSlider = QtWidgets.QSlider(self.frame)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout.addWidget(self.horizontalSlider, 0, QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cur_time = QtWidgets.QLabel(self.frame)
        self.cur_time.setObjectName("cur_time")
        self.horizontalLayout_2.addWidget(self.cur_time, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.full_time = QtWidgets.QLabel(self.frame)
        self.full_time.setObjectName("full_time")
        self.horizontalLayout_2.addWidget(self.full_time, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startButton = QtWidgets.QPushButton(self.frame)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.frame)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 2)
        self.verticalLayout_6.addWidget(self.frame)

        self.retranslateUi(Form)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.team_a_graph.setText(_translate("Form", "team_A"))
        self.team_b_graph.setText(_translate("Form", "team_B"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.bar_graph), _translate("Form", "team"))
        self.player_graph.setText(_translate("Form", "player_graph"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.line_graph), _translate("Form", "player"))
        self.video_frame1.setText(_translate("Form", "origin_frame"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.origin_view), _translate("Form", "origin"))
        self.video_frame2.setText(_translate("Form", "processing_frame"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.processing_view), _translate("Form", "processing"))
        self.cur_time.setText(_translate("Form", "cur"))
        self.full_time.setText(_translate("Form", "full"))
        self.startButton.setText(_translate("Form", "Start"))
        self.stopButton.setText(_translate("Form", "Stop"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

